---
title: "p8105_hw6_dr3168"
author: "Daniela Rochez"
date: "11/30/2021"
output: github_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(modelr)
```

```{r}
child_birthweight_df=read_csv("data/birthweight.csv")

child_birthweight_df=
  child_birthweight_df %>% 
  janitor::clean_names() %>% 
  mutate(babysex=
           recode(
             babysex,"1"= "male", "2"="female")) %>%
  mutate(frace=recode(frace, 
                      "1"= "white", "2"="black",
                      "3"="asian","4"="puerto_rican",
                      "8"="other", "9"="unknown"))%>%
  mutate(malform=
           recode(malform,"1"= "present",
                  "0"="absent")) %>% 
  mutate(mrace=recode(mrace, 
                      "1"= "white", "2"="black",
                      "3"="asian","4"="puerto_rican",
                      "8"="other")) %>% 
  mutate(babysex=as.factor(babysex),
         frace=as.factor(frace),
         mrace=as.factor(mrace),
         malform= as.factor(malform),
         momage=as.factor(momage))

```
Creating Linear Model
```{r}

lm_bwt_ppbmi = lm(bwt ~ ppbmi+babysex, data = child_birthweight_df)

child_birthweight_df %>% 
  add_residuals(lm_bwt_ppbmi) %>%
  add_predictions(lm_bwt_ppbmi) %>% 
  ggplot(aes(x = pred, y = resid))+ geom_point()

```

Cross Validation
```{r}
cv_bwt_df=
  crossv_mc(child_birthweight_df, 100) %>% 
    mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```


```{r}
cv_bwt_df=
  cv_bwt_df %>% 
   mutate(
     lm_bwt_ppbmi = 
       map(train, ~lm(bwt ~ ppbmi+babysex, 
                      data = .x)),
     lm_bwt_blength_gaweeks=
       map(train, ~lm(bwt ~ blength+gaweeks, 
                      data = .x)),
     lm_bwt_head_length_sex= 
       map(train, ~lm(bwt~bhead*blength*babysex,
                      data = .x))) %>% 
    mutate(
      rmse_bwt_ppbmi=
        map2_dbl(lm_bwt_ppbmi, test, 
                 ~rmse(model= .x, data = .y)),
      rmse_bwt_blength_gaweeks=
        map2_dbl(lm_bwt_blength_gaweeks, test, 
                 ~rmse(model= .x, data = .y)),
      rmse_bwt_head_length_sex=
        map2_dbl(lm_bwt_head_length_sex, test, 
                 ~rmse(model= .x, data = .y)))
```

```{r}
cv_bwt_df%>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```



Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
Creating Bootstrap function
```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)}
```
Drawing Samples
```{r}
boot_straps = 
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df )))

boot_straps
```
Checking to see if it works
```{r}
boot_straps %>% 
  filter(strap_number %in% 1:2) %>% 
  mutate(strap_sample = map(strap_sample, ~arrange(.x, tmin))) %>% 
  pull(strap_sample)
```
Looking at nested data, fitting the model, tidying the data, unnesting the data
```{r}
bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(strap_sample, 
                 ~lm(tmax ~ tmin, data = .x) ),
    results_tidy= map(models, broom::tidy),
    results_glance= map(models, broom::glance)) %>% 
  select(-strap_sample, -models) %>% 
  unnest(results_glance) %>% 
  unnest(results_tidy, names_repair = "unique")
```

CI for Log B0 and B1
```{r}
bootstrap_results %>% 
  group_by(strap_number) %>%
  summarize(log_b0_b1 = prod(estimate)) %>% 
  mutate(log_b0_b1= log(log_b0_b1)) %>% 
  summarize(
    ci_lower = quantile(log_b0_b1, 0.025), 
    ci_upper = quantile(log_b0_b1, 0.975))
```
CI for R Squared
```{r}
bootstrap_results %>% 
   summarize(
    ci_lower = quantile(r.squared, 0.025), 
    ci_upper = quantile(r.squared, 0.975))
```
Creating distribution of log estimates
```{r}
bootstrap_results %>% 
  group_by(strap_number) %>%
  summarize(log_b0_b1 = prod(estimate)) %>% 
  mutate(log_b0_b1= log(log_b0_b1)) %>% 
 ggplot(aes(x = log_b0_b1)) + geom_density()
```
Creating distribution of r squared estimates
```{r}
bootstrap_results %>% 
 ggplot(aes(x = r.squared)) + geom_density()
```

